spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/feed_my_sheep?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul"
    username: "root"
    password: "feedmysheep"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
#      db 변경 사항 적용 -> 향후 none
      ddl-auto: update

jwt:
  secretKey: "Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus. (1 Thessalonians 5:16-18)"
  refreshExpiry: 31536000000
  accessExpiry: 86400000

twilio:
  accountSid: "AC8edd3e64ee51444b1a3ea11d5268edee"
  authToken: "c63a826d7c5e799748ce4a9e78900a5a"
  fromPhoneNumber: "+17067703741"

verification:
  maxCodeGenNum: 5
  maxCodeTryNum: 5